services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      - db
      - redis
    networks:
      - event_network

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - event_network

  redis:
    image: redis:7.4.0
    env_file:
      - .env
    ports:
      - "6380:6379"
    networks:
      - event_network

  localstack:
    image: localstack/localstack
    ports:
      - "4568:4566"
    env_file:
      - .env
    volumes:
          - localstack_data:/var/lib/localstack
    networks:
      - event_network

  celery_worker:
    build: .
    env_file:
      - .env
    entrypoint: [ "./entrypoint.sh" ]
    command: celery -A eventservice worker --loglevel=info
    depends_on:
      - api
      - redis
    restart: always
    networks:
      - event_network

volumes:
  postgres_data:
  localstack_data:


networks:
  event_network:
    driver: bridge