version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: